# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 20, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setGeometry(QtCore.QRect(570, 470, 75, 23))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.matrix_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.matrix_txt.setGeometry(QtCore.QRect(440, 250, 281, 101))
        self.matrix_txt.setObjectName("matrix_txt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.encrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_btn.setGeometry(QtCore.QRect(180, 470, 75, 23))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 350, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 90, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.plaintext_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.plaintext_txt.setGeometry(QtCore.QRect(130, 150, 591, 71))
        self.plaintext_txt.setObjectName("plaintext_txt")
        self.ciphertext_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.ciphertext_txt.setGeometry(QtCore.QRect(130, 370, 591, 91))
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.key_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.key_txt.setGeometry(QtCore.QRect(130, 250, 241, 31))
        self.key_txt.setObjectName("key_txt")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 260, 47, 13))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.decrypt_btn.setText(_translate("MainWindow", "Decrypt"))
        self.label_3.setText(_translate("MainWindow", "Plain Text:"))
        self.encrypt_btn.setText(_translate("MainWindow", "Encrypt"))
        self.label_4.setText(_translate("MainWindow", "Key:"))
        self.label_5.setText(_translate("MainWindow", "Cipher Text:"))
        self.label_2.setText(_translate("MainWindow", "Nguyễn Thị Thuý Hiền - 2280600911"))
        self.label_6.setText(_translate("MainWindow", "Matrix:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
